name: Build and Deploy Homeless Bot

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Replace with your Java version if different
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build # Replace with your actual build command if different
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: homeless-bot-jar
          path: build/libs/*.jar # Adjust this path if your JAR is located elsewhere or has a specific name

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      APP_DIR: "/opt/homeless-bot"
      SERVICE_NAME: "homeless-bot"
      JAR_NAME: "app.jar"
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: homeless-bot-jar
          path: ./artifact

      - name: Copy JAR to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: "./artifact/homeless-bot-1.0-SNAPSHOT.jar"
          target: "/opt/homeless-bot/app.jar"

      - name: Run deploy script on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            set -e

            sudo mkdir -p ${{ env.APP_DIR }}/src/main/resources

            # Create environment files
            sudo mkdir -p ${{ env.APP_DIR }}/src
            echo "tg.bot.token=${{ secrets.TG_BOT_TOKEN }}" | sudo tee ${{ env.APP_DIR }}/src/app.env > /dev/null
            echo "spreadsheet.id=${{ secrets.SPREADSHEET_ID }}" | sudo tee -a ${{ env.APP_DIR }}/src/app.env > /dev/null

            echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' | sudo tee ${{ env.APP_DIR }}/src/main/resources/credentials.json > /dev/null

            # Setup systemd service file
            sudo tee /etc/systemd/system/${{ env.SERVICE_NAME }}.service > /dev/null <<EOF
            [Unit]
            Description=Homeless Bot Service
            After=network.target

            [Service]
            User=${{ secrets.VPS_USER }}
            Group=${{ secrets.VPS_USER }}
            WorkingDirectory=${{ env.APP_DIR }}
            ExecStart=/usr/bin/java -jar ${{ env.APP_DIR }}/${{ env.JAR_NAME }}
            SuccessExitStatus=143
            Restart=always
            RestartSec=5s
            StandardOutput=journal
            StandardError=journal
            SyslogIdentifier=${{ env.SERVICE_NAME }}

            [Install]
            WantedBy=multi-user.target
            EOF

            sudo systemctl daemon-reload
            sudo systemctl enable ${{ env.SERVICE_NAME }}
            sudo systemctl restart ${{ env.SERVICE_NAME }}

            echo "Deployment complete. Check logs: journalctl -u ${{ env.SERVICE_NAME }} -f"